name: Build Trevors Portfolio

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: |
          curl -X POST -H 'Content-type:application/json' --data "{\"text\":\"$GITHUB_REPOSITORY - Starting build by $GITHUB_ACTOR on $GITHUB_EVENT_NAME from $GITHUB_REF...\"}" $SLACK_URL
          yarn && yarn build
          aws s3 cp \
            --recursive \
            ./build/ s3://www.trevormdavis.com
          curl -X POST -H 'Content-type:application/json' --data "{\"text\":\"$GITHUB_REPOSITORY - Build complete by $GITHUB_ACTOR on $GITHUB_EVENT_NAME from $GITHUB_REF. \"}" $SLACK_URL
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        if: failure()
        env:
          SLACK_CHANNEL: trevor-portfolio
          SLACK_COLOR: "#3278BD"
          SLACK_ICON: https://upload.wikimedia.org/wikipedia/en/c/c5/Bob_the_builder.jpg
          SLACK_MESSAGE: "$GITHUB_REPOSITORY - Build failed...you idiot."
          SLACK_TITLE: Fail
          SLACK_USERNAME: Trevor the Engineer
          SLACK_WEBHOOK: ${{ secrets.SLACK_URL }}
